global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: production
    app: emptytruck

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:5000"]
    metrics_path: /metrics

  - job_name: "mongodb"
    static_configs:
      - targets: ["mongo:9216"]

  - job_name: "redis"
    static_configs:
      - targets: ["redis:9121"]

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:9113"]
